### ISSUE TITLE
imageWithString method isn't working

### ISSUE THREAD

**Issue by itsaark** [ridvank/UIImageViewWithWords#8]
I'm trying to call the `imageWithString` method. But nothing seems to appear on the `imageView`

**Comment by ridvank** [comment]
Hi @itsaark ,
Are you sure that it does not work?
I have tested it and it works, however size is small as I did not expected. I will fix the size.

**Comment by itsaark** [comment]
Update: I'm sorry, there was a logic error in my code. `imageWithString` is working, but the text size is too small. I guess that can be fixed using fontAttributes right?

**Comment by ridvank** [comment]
I have fixed the text size issue. Can you run `pod update` again? If any error occurs we can reopen the issue.

**Comment by itsaark** [comment]
Did an update
`imageWithString` is gone. I'm getting the following error: `UIImageview` has no member `imageWithString`.

**Comment by ridvank** [comment]
You are able to use with `imageView.image(with: "Lorem Ipsum")` now. It's been updated also 👍

**Comment by itsaark** [comment]
Thank you! 👍
